### ISSUE TITLE
[EPIC] GTFS Schedules Harvesting - phase 2

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/mobility-database-interface#248]
**Description:**

[OpenMobilityData](https://openmobilitydata.org/) have been harvested to [the Mobility Database](http://mobilitydatabase.org/wiki/Main_Page). While the Catalog of GTFS Schedules contains now around 1000 sources, it is not exhaustive since it does not contain every existing GTFS Schedule. Harvesting other known repositories is then necessary. 

**Documentation:**

[Other known GTFS Schedules repositories](https://docs.google.com/spreadsheets/d/1Q96KDppKsn2khdrkraZCQ7T_qRSfwj7WsvqXvuMt4Bc/edit?resourcekey#gid=819781650)

**This issue regroups several issues from the same subproject. To be closed once the subproject is done:**

- [x] List sources from Transitland #163
- [x] Compare Transitland's sources with database sources
- [x] Harvesting Transitland's sources that are not existing on the database
- [ ] List sources from Oregon
- [ ] Compare Oregon's sources with database sources
- [ ] Harvesting Oregon's sources that are not existing on the database
- [ ] List sources from European Transport Feeds
- [ ] Compare European Transport Feeds' sources with database sources
- [ ] Harvesting European Transport Feeds' sources that are not existing on the database
- [ ] List sources from EU National Access Points
- [ ] Compare EU National Access Points' sources with database sources
- [ ] Harvesting EU National Access Points' sources that are not existing on the database
